-- Generated by `npx drizzle-kit generate --name customer_orders`, then
-- hand-adjusted: drizzle-kit emitted `ADD COLUMN "buyer_kind" text NOT NULL`
-- with no default, which fails outright against any existing row. Backfill
-- order matters (design.md "Migration / Rollout"): add the column nullable,
-- backfill every existing row to 'RESELLER' (the only buyer kind that could
-- have placed an order before this migration), THEN set it NOT NULL — the
-- CHECKs are added only after the column is fully populated and closed.
ALTER TABLE "sales_order" DROP CONSTRAINT "sales_order_status_check";--> statement-breakpoint
ALTER TABLE "sales_order" DROP CONSTRAINT "sales_order_fulfilled_at_check";--> statement-breakpoint
ALTER TABLE "sales_order" ALTER COLUMN "wallet_entry_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "sales_order" ADD COLUMN "buyer_kind" text;--> statement-breakpoint
UPDATE "sales_order" SET "buyer_kind" = 'RESELLER';--> statement-breakpoint
ALTER TABLE "sales_order" ALTER COLUMN "buyer_kind" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "sales_order" ADD COLUMN "provider_account_id" uuid;--> statement-breakpoint
ALTER TABLE "sales_order" ADD CONSTRAINT "sales_order_provider_account_id_provider_account_id_fk" FOREIGN KEY ("provider_account_id") REFERENCES "public"."provider_account"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sales_order" ADD CONSTRAINT "sales_order_buyer_kind_check" CHECK ("sales_order"."buyer_kind" IN ('RESELLER', 'CUSTOMER'));--> statement-breakpoint
ALTER TABLE "sales_order" ADD CONSTRAINT "sales_order_funding_check" CHECK (("sales_order"."buyer_kind" = 'RESELLER' AND "sales_order"."wallet_entry_id" IS NOT NULL AND "sales_order"."provider_account_id" IS NULL)
       OR ("sales_order"."buyer_kind" = 'CUSTOMER' AND "sales_order"."wallet_entry_id" IS NULL AND "sales_order"."provider_account_id" IS NOT NULL));--> statement-breakpoint
ALTER TABLE "sales_order" ADD CONSTRAINT "sales_order_status_buyer_check" CHECK (("sales_order"."buyer_kind" = 'RESELLER' AND "sales_order"."status" IN ('PENDING', 'FULFILLED', 'CANCELLED'))
       OR ("sales_order"."buyer_kind" = 'CUSTOMER'));--> statement-breakpoint
ALTER TABLE "sales_order" ADD CONSTRAINT "sales_order_status_check" CHECK ("sales_order"."status" IN ('AWAITING_PAYMENT', 'PENDING', 'FULFILLED', 'CANCELLED'));--> statement-breakpoint
ALTER TABLE "sales_order" ADD CONSTRAINT "sales_order_fulfilled_at_check" CHECK (("sales_order"."status" = 'FULFILLED') = ("sales_order"."fulfilled_at" IS NOT NULL));
