-- Payment validation: a top-up becomes a CLAIM that a human approves, and the
-- credit is appended only on approval.
--
-- Until now `topUpBalance` appended a TOPUP entry the instant an operator
-- clicked the button: no proof, no second pair of eyes, no record that the
-- money had actually arrived. `payment_request` is the record that was
-- missing, and `payment_request_credit_check` is what makes "approved but
-- never credited" — and its mirror, "credited but never approved" —
-- unrepresentable rather than merely discouraged.
--
-- `payment_request_reference_approved_idx` is PARTIAL on purpose (backlog A8):
-- the same reference legitimately reappears on a rejected claim and its
-- corrected resubmission, so uniqueness is scoped to the rows where it means
-- something — the approved ones that actually moved money. `lower(...)`
-- mirrors `referenceKey()` in the domain.
--
-- Generated by drizzle-kit; the RLS block at the end is appended by hand,
-- exactly as 0015 explains, because drizzle-kit knows nothing about Supabase's
-- roles and has never emitted it.

CREATE TABLE "payment_request" (
	"id" uuid PRIMARY KEY NOT NULL,
	"reseller_id" uuid NOT NULL,
	"amount_minor" bigint NOT NULL,
	"currency" char(3) NOT NULL,
	"method" text NOT NULL,
	"reference" text NOT NULL,
	"proof_url" text NOT NULL,
	"status" text NOT NULL,
	"wallet_entry_id" uuid,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"reviewed_by" uuid,
	"reviewed_at" timestamp with time zone,
	"decision_note" text,
	CONSTRAINT "payment_request_wallet_entry_id_unique" UNIQUE("wallet_entry_id"),
	CONSTRAINT "payment_request_status_check" CHECK ("payment_request"."status" IN ('PENDING', 'APPROVED', 'REJECTED')),
	CONSTRAINT "payment_request_method_check" CHECK ("payment_request"."method" IN ('BANK_TRANSFER', 'NEQUI', 'DAVIPLATA', 'BINANCE_PAY', 'CASH', 'OTHER')),
	CONSTRAINT "payment_request_amount_minor_check" CHECK ("payment_request"."amount_minor" > 0),
	CONSTRAINT "payment_request_currency_check" CHECK ("payment_request"."currency" ~ '^[A-Z]{3}$'),
	CONSTRAINT "payment_request_reference_check" CHECK (length(btrim("payment_request"."reference")) > 0),
	CONSTRAINT "payment_request_proof_check" CHECK (length(btrim("payment_request"."proof_url")) > 0),
	CONSTRAINT "payment_request_credit_check" CHECK (("payment_request"."status" = 'APPROVED') = ("payment_request"."wallet_entry_id" IS NOT NULL)),
	CONSTRAINT "payment_request_review_check" CHECK (("payment_request"."status" = 'PENDING') = ("payment_request"."reviewed_by" IS NULL AND "payment_request"."reviewed_at" IS NULL)),
	CONSTRAINT "payment_request_rejection_reason_check" CHECK ("payment_request"."status" <> 'REJECTED' OR length(btrim(coalesce("payment_request"."decision_note", ''))) > 0)
);
--> statement-breakpoint
CREATE TABLE "topup_settings" (
	"id" boolean PRIMARY KEY DEFAULT true NOT NULL,
	"min_amount_minor" bigint DEFAULT 10000 NOT NULL,
	"max_amount_minor" bigint DEFAULT 5000000 NOT NULL,
	"currency" char(3) DEFAULT 'COP' NOT NULL,
	"updated_by" uuid,
	"updated_at" timestamp with time zone,
	CONSTRAINT "topup_settings_singleton_check" CHECK ("topup_settings"."id" = true),
	CONSTRAINT "topup_settings_min_check" CHECK ("topup_settings"."min_amount_minor" > 0),
	CONSTRAINT "topup_settings_range_check" CHECK ("topup_settings"."max_amount_minor" >= "topup_settings"."min_amount_minor"),
	CONSTRAINT "topup_settings_currency_check" CHECK ("topup_settings"."currency" ~ '^[A-Z]{3}$')
);
--> statement-breakpoint
ALTER TABLE "payment_request" ADD CONSTRAINT "payment_request_wallet_entry_id_wallet_entry_id_fk" FOREIGN KEY ("wallet_entry_id") REFERENCES "public"."wallet_entry"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payment_request" ADD CONSTRAINT "payment_request_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payment_request" ADD CONSTRAINT "payment_request_reviewed_by_users_id_fk" FOREIGN KEY ("reviewed_by") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "topup_settings" ADD CONSTRAINT "topup_settings_updated_by_users_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "payment_request_reseller_idx" ON "payment_request" USING btree ("reseller_id","created_at");--> statement-breakpoint
CREATE INDEX "payment_request_status_idx" ON "payment_request" USING btree ("status","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "payment_request_reference_approved_idx" ON "payment_request" USING btree (lower("reference")) WHERE "payment_request"."status" = 'APPROVED';--> statement-breakpoint
-- The same lockdown 0004 installed and 0015 re-applied, for the two tables
-- this file adds. No policies, deliberately: no policy means no rows for any
-- role lacking BYPASSRLS. The application connects as `postgres`, which holds
-- it, so its own queries are unaffected.
--
-- It matters here as much as it did for `withdrawal_methods`: `proof_url`
-- points at a customer's payment receipt, and `reference` is a real bank
-- transfer reference.
ALTER TABLE "payment_request" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "topup_settings" ENABLE ROW LEVEL SECURITY;