-- Block B: the platform's own logins on a SUPPLIER's reseller panel, and the
-- credit balances those panels report back.
--
-- This is NOT `provider_account` and must never be confused with it. That
-- table (0009) is CUSTOMER-owned, tenant-scoped by `reseller_id`, and holds no
-- credential and no lifecycle by spec ("PA: No Credential Or Lifecycle Fields
-- Exist", with an information_schema tripwire guarding it). It is the
-- DESTINATION of a recharge. This one is the SOURCE.
--
-- `source_account_credit` IS A MIRROR, NOT A LEDGER, and that decides its
-- shape. The rows are replaced wholesale on every successful sync: no running
-- total, no debit, no credit, no history. The operator can spend from the
-- supplier's panel by hand at any moment, so any figure this platform computed
-- for itself would be wrong by lunchtime. `plan` therefore carries no CHECK —
-- it is the SUPPLIER's catalogue, and the day they add a plan it must reach
-- the screen without a migration. `period` does carry one, because the panel
-- states those two meanings itself ("1 punto = 1 mes" / "1 punto = 12 meses").
--
-- No `service_id`: the supplier sells by device count, not by streaming
-- service. No credential column: the panel asks for a verification code at
-- login and never during a recharge, so a human logs in by hand and the
-- automation inherits the session.
--
-- Generated by drizzle-kit; the RLS block at the end is appended by hand,
-- exactly as 0015 and 0016 explain, because drizzle-kit knows nothing about
-- Supabase's roles and has never emitted it.

CREATE TABLE "source_account" (
	"id" uuid PRIMARY KEY NOT NULL,
	"panel_url" text NOT NULL,
	"panel_username" text NOT NULL,
	"label" text,
	"connection_status" text DEFAULT 'NEVER_CONNECTED' NOT NULL,
	"last_sync_at" timestamp with time zone,
	"last_sync_error" text,
	"consecutive_failures" integer DEFAULT 0 NOT NULL,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"archived_at" timestamp with time zone,
	CONSTRAINT "source_account_panel_url_check" CHECK (length(btrim("source_account"."panel_url")) > 0),
	CONSTRAINT "source_account_panel_username_check" CHECK (length(btrim("source_account"."panel_username")) > 0),
	CONSTRAINT "source_account_connection_status_check" CHECK ("source_account"."connection_status" IN ('NEVER_CONNECTED', 'CONNECTED', 'LOGIN_ERROR', 'REQUIRES_2FA', 'BLOCKED')),
	CONSTRAINT "source_account_consecutive_failures_check" CHECK ("source_account"."consecutive_failures" >= 0),
	CONSTRAINT "source_account_sync_clock_check" CHECK (("source_account"."connection_status" = 'NEVER_CONNECTED') = ("source_account"."last_sync_at" IS NULL))
);
--> statement-breakpoint
CREATE TABLE "source_account_credit" (
	"id" uuid PRIMARY KEY NOT NULL,
	"source_account_id" uuid NOT NULL,
	"plan" text NOT NULL,
	"period" text NOT NULL,
	"points" integer NOT NULL,
	"synced_at" timestamp with time zone NOT NULL,
	CONSTRAINT "source_account_credit_plan_check" CHECK (length(btrim("source_account_credit"."plan")) > 0),
	CONSTRAINT "source_account_credit_period_check" CHECK ("source_account_credit"."period" IN ('MONTHLY', 'ANNUAL')),
	CONSTRAINT "source_account_credit_points_check" CHECK ("source_account_credit"."points" >= 0)
);
--> statement-breakpoint
ALTER TABLE "source_account" ADD CONSTRAINT "source_account_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "source_account_credit" ADD CONSTRAINT "source_account_credit_source_account_id_source_account_id_fk" FOREIGN KEY ("source_account_id") REFERENCES "public"."source_account"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "source_account_status_idx" ON "source_account" USING btree ("connection_status","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "source_account_identity_uniq" ON "source_account" USING btree ("panel_url",lower("panel_username")) WHERE "source_account"."archived_at" IS NULL;--> statement-breakpoint
CREATE INDEX "source_account_credit_account_idx" ON "source_account_credit" USING btree ("source_account_id");--> statement-breakpoint
CREATE UNIQUE INDEX "source_account_credit_bucket_uniq" ON "source_account_credit" USING btree ("source_account_id",lower("plan"),"period");--> statement-breakpoint
-- The same lockdown 0004 installed and 0015 re-applied, for the two tables
-- this file adds. No policies, deliberately: no policy means no rows for any
-- role lacking BYPASSRLS. The application connects as `postgres`, which holds
-- it, so its own queries are unaffected.
--
-- It matters here even without a password column: `panel_url` and
-- `panel_username` together name the supplier and the account the whole
-- operation depends on, `last_sync_error` carries back whatever the supplier's
-- page said, and the credit rows are a live read on how much stock the
-- business is holding.
ALTER TABLE "source_account" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "source_account_credit" ENABLE ROW LEVEL SECURITY;