-- The recharge protocol's durable half: one row per attempt against the
-- supplier's panel, written BEFORE the click.
--
-- A web form has no idempotency key. The automation presses "Aceptar", the
-- connection drops, and nothing on either side can say whether the supplier
-- applied the recharge. Retrying might charge a customer twice; not retrying
-- might leave them unpaid. This table is what makes the question answerable:
-- `accumulated_before` holds "Puntos acumulados" as read immediately before
-- the attempt, from a counter the panel only ever increases.
--
--   after = before + points  -> CONFIRMED
--   after = before           -> FAILED     (the only state safe to retry)
--   anything else            -> UNVERIFIED (a human opens the panel)
--
-- `recharge_attempt_confirmed_check` and `..._failed_check` encode those two
-- definitions as CHECKs rather than trusting the code to honour them. A status
-- written without the matching arithmetic fails the INSERT, instead of
-- surfacing three weeks later when somebody audits a customer's balance.
--
-- `recharge_attempt_open_idx` is PARTIAL: the recovery queue only ever holds
-- unsettled rows, so it stays small no matter how much history accumulates.
--
-- Generated by drizzle-kit; the RLS block at the end is appended by hand,
-- exactly as 0015, 0016 and 0017 explain, because drizzle-kit knows nothing
-- about Supabase's roles and has never emitted it.

CREATE TABLE "recharge_attempt" (
	"id" uuid PRIMARY KEY NOT NULL,
	"source_account_id" uuid NOT NULL,
	"target_account" text NOT NULL,
	"plan" text NOT NULL,
	"period" text NOT NULL,
	"points" integer NOT NULL,
	"status" text NOT NULL,
	"accumulated_before" integer NOT NULL,
	"accumulated_after" integer,
	"failure_detail" text,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"submitted_at" timestamp with time zone,
	"settled_at" timestamp with time zone,
	CONSTRAINT "recharge_attempt_target_check" CHECK (length(btrim("recharge_attempt"."target_account")) > 0),
	CONSTRAINT "recharge_attempt_plan_check" CHECK (length(btrim("recharge_attempt"."plan")) > 0),
	CONSTRAINT "recharge_attempt_period_check" CHECK ("recharge_attempt"."period" IN ('MONTHLY', 'ANNUAL')),
	CONSTRAINT "recharge_attempt_points_check" CHECK ("recharge_attempt"."points" >= 1),
	CONSTRAINT "recharge_attempt_status_check" CHECK ("recharge_attempt"."status" IN ('PENDING', 'SUBMITTED', 'CONFIRMED', 'FAILED', 'UNVERIFIED')),
	CONSTRAINT "recharge_attempt_anchor_check" CHECK ("recharge_attempt"."accumulated_before" >= 0),
	CONSTRAINT "recharge_attempt_after_check" CHECK ("recharge_attempt"."accumulated_after" IS NULL OR "recharge_attempt"."accumulated_after" >= 0),
	CONSTRAINT "recharge_attempt_settled_check" CHECK (("recharge_attempt"."status" IN ('PENDING', 'SUBMITTED')) = ("recharge_attempt"."settled_at" IS NULL)),
	CONSTRAINT "recharge_attempt_submitted_check" CHECK ("recharge_attempt"."status" <> 'SUBMITTED' OR "recharge_attempt"."submitted_at" IS NOT NULL),
	CONSTRAINT "recharge_attempt_confirmed_check" CHECK ("recharge_attempt"."status" <> 'CONFIRMED' OR "recharge_attempt"."accumulated_after" = "recharge_attempt"."accumulated_before" + "recharge_attempt"."points"),
	CONSTRAINT "recharge_attempt_failed_check" CHECK ("recharge_attempt"."status" <> 'FAILED' OR "recharge_attempt"."accumulated_after" = "recharge_attempt"."accumulated_before"),
	CONSTRAINT "recharge_attempt_unverified_check" CHECK ("recharge_attempt"."status" <> 'UNVERIFIED' OR length(btrim(coalesce("recharge_attempt"."failure_detail", ''))) > 0)
);
--> statement-breakpoint
ALTER TABLE "recharge_attempt" ADD CONSTRAINT "recharge_attempt_source_account_id_source_account_id_fk" FOREIGN KEY ("source_account_id") REFERENCES "public"."source_account"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "recharge_attempt" ADD CONSTRAINT "recharge_attempt_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "recharge_attempt_source_idx" ON "recharge_attempt" USING btree ("source_account_id","created_at");--> statement-breakpoint
CREATE INDEX "recharge_attempt_open_idx" ON "recharge_attempt" USING btree ("created_at") WHERE "recharge_attempt"."status" IN ('PENDING', 'SUBMITTED');--> statement-breakpoint
-- The same lockdown 0004 installed and 0015 re-applied. No policies,
-- deliberately: no policy means no rows for any role lacking BYPASSRLS.
--
-- It matters as much here as for `payment_request`: `target_account` is a
-- customer's real phone number, and the table as a whole is a complete record
-- of who was recharged, when and how much.
ALTER TABLE "recharge_attempt" ENABLE ROW LEVEL SECURITY;
