import path from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { sql } from "drizzle-orm";
import { migrate } from "drizzle-orm/pglite/migrator";

import { createTestDb, closeTestDb, type TestDb } from "../../../../tests/support/pglite-db";

/**
 * IT: Exactly One Role Per User — proven at the SCHEMA level against real
 * Postgres (PGlite).
 *
 * The `users` DDL comes from the REAL checked-in migration: `migrate()`
 * applies drizzle/0001 (generated by `npx drizzle-kit generate` from
 * identity.schema.ts via src/shared/db/schema.ts) on top of drizzle/0000.
 * Before M9 these tests derived the DDL through drizzle-kit's own diff
 * engine (generateMigration) because 0001 did not exist yet; that helper
 * was removed once the migration landed, so the constraints asserted here
 * are now the ones that actually ship.
 */
const DRIZZLE_DIR = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "..",
  "..",
  "drizzle",
);

async function insertUser(
  testDb: TestDb,
  id: string,
  email: string,
  role: string,
  priceTierId?: string,
): Promise<void> {
  // `password_hash` is NOT NULL (drizzle/0002): a stand-in PHC string keeps
  // these schema tests about the constraints they actually assert. Real
  // argon2id output is exercised in node-rs-argon2-hasher.test.ts.
  await testDb.db.execute(
    sql`INSERT INTO users (id, email, password_hash, role, price_tier_id, created_at) VALUES (${id}, ${email}, '$argon2id$stand-in', ${role}, ${priceTierId ?? null}, now())`,
  );
}

async function insertPriceTier(testDb: TestDb, id: string, code: string): Promise<void> {
  await testDb.db.execute(
    sql`INSERT INTO price_tier (id, code, name, created_at) VALUES (${id}, ${code}, ${code}, now())`,
  );
}

describe("identity schema — exactly one role per user (IT: Exactly One Role Per User)", () => {
  let testDb: TestDb;

  beforeEach(async () => {
    testDb = await createTestDb();
    // Catalog schema first: drizzle/0000 ships price_tier, which
    // users.price_tier_id references; drizzle/0001 ships the users DDL on
    // top, in exactly the order a fresh database applies them.
    await migrate(testDb.db, { migrationsFolder: DRIZZLE_DIR });
  });

  afterEach(async () => {
    await closeTestDb(testDb);
  });

  it("rejects persisting a user with role 'SUPERADMIN'", async () => {
    // `role` is text + CHECK, not a Postgres enum (design.md "Decision: role
    // becomes text + CHECK; the user_role enum is dropped"), so an invalid
    // role is rejected by `users_role_check`, not an enum-cast error. Drizzle
    // wraps the driver error in DrizzleQueryError; the Postgres rejection is
    // on `.cause`.
    await expect(
      insertUser(testDb, "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa", "super@example.com", "SUPERADMIN"),
    ).rejects.toMatchObject({
      cause: expect.objectContaining({
        message: expect.stringMatching(/violates check constraint "users_role_check"/),
      }),
    });
  });

  it("persists a CUSTOMER user carrying a price tier (IT: CUSTOMER role accepted)", async () => {
    await insertPriceTier(testDb, "aaaaaaaa-1111-4111-8111-111111111111", "RETAIL");
    await insertUser(
      testDb,
      "bbbbbbbb-1111-4111-8111-111111111111",
      "customer@example.com",
      "CUSTOMER",
      "aaaaaaaa-1111-4111-8111-111111111111",
    );

    const result = await testDb.db.execute<{ email: string; role: string }>(
      sql`SELECT email, role FROM users WHERE id = 'bbbbbbbb-1111-4111-8111-111111111111'`,
    );
    expect(result.rows).toEqual([{ email: "customer@example.com", role: "CUSTOMER" }]);
  });

  it("persists ADMIN and RESELLER users", async () => {
    // IT: One Price Tier Per Reseller — a RESELLER is only persisted once a
    // price tier is assigned (previously this insert passed tier-less).
    await insertPriceTier(testDb, "77777777-7777-4777-8777-777777777777", "DEFAULT");
    await insertUser(testDb, "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb", "admin@example.com", "ADMIN");
    await insertUser(
      testDb,
      "cccccccc-cccc-4ccc-8ccc-cccccccccccc",
      "reseller@example.com",
      "RESELLER",
      "77777777-7777-4777-8777-777777777777",
    );

    const result = await testDb.db.execute<{ email: string; role: string }>(
      sql`SELECT email, role FROM users ORDER BY email`,
    );

    expect(result.rows).toEqual([
      { email: "admin@example.com", role: "ADMIN" },
      { email: "reseller@example.com", role: "RESELLER" },
    ]);
  });

  it("rejects a second user whose email collides case-insensitively (IT: Globally Unique Email)", async () => {
    await insertUser(testDb, "dddddddd-dddd-4ddd-8ddd-dddddddddddd", "owner@example.com", "ADMIN");

    // The colliding row is a RESELLER, so it needs a price tier: the
    // users_reseller_requires_tier CHECK would otherwise reject it before the
    // unique index gets a chance to (IT: One Price Tier Per Reseller).
    await insertPriceTier(testDb, "88888888-8888-4888-8888-888888888888", "TIER_C");
    // The two addresses differ ONLY by case — a plain UNIQUE(email) would
    // accept the second one; only the functional index on lower(email) can
    // reject it. Asserting the index name in the violation proves the
    // rejection came from `users_email_lower_uniq`, not another constraint.
    await expect(
      insertUser(
        testDb,
        "eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee",
        "Owner@Example.com",
        "RESELLER",
        "88888888-8888-4888-8888-888888888888",
      ),
    ).rejects.toMatchObject({
      cause: expect.objectContaining({
        message: expect.stringMatching(
          /duplicate key value violates unique constraint "users_email_lower_uniq"/,
        ),
      }),
    });

    // Triangulation: an email differing beyond case is NOT rejected — the
    // uniqueness applies to the case-folded address, not to the whole
    // `users` table. (RESELLER needs the tier to satisfy the new CHECK.)
    await insertUser(
      testDb,
      "ffffffff-ffff-4fff-8fff-ffffffffffff",
      "other@example.com",
      "RESELLER",
      "88888888-8888-4888-8888-888888888888",
    );
    const result = await testDb.db.execute<{ email: string }>(
      sql`SELECT email FROM users WHERE id = 'ffffffff-ffff-4fff-8fff-ffffffffffff'`,
    );
    expect(result.rows).toEqual([{ email: "other@example.com" }]);
  });

  it("declares the users_role_check CHECK constraint in the generated DDL", async () => {
    const result = await testDb.db.execute<{ conname: string; consrc: string }>(
      sql`SELECT conname, pg_get_constraintdef(oid) AS consrc FROM pg_constraint WHERE conname = 'users_role_check'`,
    );

    expect(result.rows).toHaveLength(1);
    expect(result.rows[0].consrc).toContain("'ADMIN'");
    expect(result.rows[0].consrc).toContain("'RESELLER'");
    expect(result.rows[0].consrc).toContain("'CUSTOMER'");
  });

  it("carries reseller_id and no parent/hierarchy column (IT: Single-Level Reseller Ownership)", async () => {
    // The ownership axis is exactly one `reseller_id` column; the design
    // forbids a `parent_id` / recursive ownership chain ("there is no
    // parent_id column to add", design.md "Schema-level answers"). Asserted
    // against real Postgres (PGlite) so the future migration cannot drift.
    const result = await testDb.db.execute<{ column_name: string }>(
      sql`SELECT column_name FROM information_schema.columns WHERE table_name = 'users' ORDER BY column_name`,
    );

    expect(result.rows.map((row) => row.column_name)).toContain("reseller_id");
    expect(result.rows.map((row) => row.column_name)).not.toContain("parent_id");
    expect(result.rows.map((row) => row.column_name)).not.toContain("parentId");
  });
});

describe("identity schema — tier requirement matches role (IT: Tier Requirement Matches Role)", () => {
  let testDb: TestDb;

  beforeEach(async () => {
    testDb = await createTestDb();
    // Catalog schema first (drizzle/0000 ships price_tier, the FK target of
    // users.price_tier_id); drizzle/0001 ships the users DDL on top, in the
    // same order a fresh database applies them.
    await migrate(testDb.db, { migrationsFolder: DRIZZLE_DIR });
  });

  afterEach(async () => {
    await closeTestDb(testDb);
  });

  // "Activation" has no is_active column in this design (deactivated_at only),
  // so the schema-level guard IS the activation guard: inserting an active
  // RESELLER row (deactivated_at NULL) without a tier must be rejected by the
  // users_tier_matches_role CHECK (design.md "Schema-level answers").
  it("rejects activating a RESELLER with no assigned price tier", async () => {
    await expect(
      insertUser(testDb, "11111111-1111-4111-8111-111111111111", "tierless@example.com", "RESELLER"),
    ).rejects.toMatchObject({
      cause: expect.objectContaining({
        message: expect.stringMatching(/violates check constraint "users_tier_matches_role"/),
      }),
    });
  });

  // IT: Tier Requirement Matches Role — the symmetry is full: CUSTOMER is
  // held to the exact same tier requirement as RESELLER.
  it("rejects activating a CUSTOMER with no assigned price tier", async () => {
    await expect(
      insertUser(testDb, "77777777-1111-4111-8111-111111111111", "tierless-customer@example.com", "CUSTOMER"),
    ).rejects.toMatchObject({
      cause: expect.objectContaining({
        message: expect.stringMatching(/violates check constraint "users_tier_matches_role"/),
      }),
    });
  });

  it("persists an ADMIN with no price tier", async () => {
    await insertUser(testDb, "22222222-2222-4222-8222-222222222222", "admin@example.com", "ADMIN");

    const result = await testDb.db.execute<{ email: string; role: string }>(
      sql`SELECT email, role FROM users WHERE id = '22222222-2222-4222-8222-222222222222'`,
    );

    expect(result.rows).toEqual([{ email: "admin@example.com", role: "ADMIN" }]);
  });

  it("persists a RESELLER once a price tier is assigned", async () => {
    await insertPriceTier(testDb, "33333333-3333-4333-8333-333333333333", "TIER_A");
    await insertUser(
      testDb,
      "44444444-4444-4444-8444-444444444444",
      "tiered@example.com",
      "RESELLER",
      "33333333-3333-4333-8333-333333333333",
    );

    const result = await testDb.db.execute<{ email: string; role: string }>(
      sql`SELECT email, role FROM users WHERE id = '44444444-4444-4444-8444-444444444444'`,
    );

    expect(result.rows).toEqual([{ email: "tiered@example.com", role: "RESELLER" }]);
  });

  it("persists a CUSTOMER once a price tier is assigned", async () => {
    await insertPriceTier(testDb, "88888888-3333-4333-8333-333333333333", "TIER_RETAIL");
    await insertUser(
      testDb,
      "99999999-4444-4444-8444-444444444444",
      "tiered-customer@example.com",
      "CUSTOMER",
      "88888888-3333-4333-8333-333333333333",
    );

    const result = await testDb.db.execute<{ email: string; role: string }>(
      sql`SELECT email, role FROM users WHERE id = '99999999-4444-4444-8444-444444444444'`,
    );

    expect(result.rows).toEqual([{ email: "tiered-customer@example.com", role: "CUSTOMER" }]);
  });

  it("rejects an ADMIN with an assigned price tier", async () => {
    // The design DDL is symmetric: the CHECK also demands ADMIN rows carry no
    // tier ((role='ADMIN' AND price_tier_id IS NULL)).
    await insertPriceTier(testDb, "55555555-5555-4555-8555-555555555555", "TIER_B");
    await expect(
      insertUser(
        testDb,
        "66666666-6666-4666-8666-666666666666",
        "misconfigured-admin@example.com",
        "ADMIN",
        "55555555-5555-4555-8555-555555555555",
      ),
    ).rejects.toMatchObject({
      cause: expect.objectContaining({
        message: expect.stringMatching(/violates check constraint "users_tier_matches_role"/),
      }),
    });
  });

  it("declares the users_tier_matches_role CHECK constraint in the generated DDL", async () => {
    const result = await testDb.db.execute<{ conname: string; consrc: string }>(
      sql`SELECT conname, pg_get_constraintdef(oid) AS consrc FROM pg_constraint WHERE conname = 'users_tier_matches_role'`,
    );

    expect(result.rows).toHaveLength(1);
    expect(result.rows[0].consrc).toContain("'RESELLER'");
    expect(result.rows[0].consrc).toContain("'CUSTOMER'");
    expect(result.rows[0].consrc).toContain("'ADMIN'");
    expect(result.rows[0].consrc).toContain("price_tier_id");
  });
});

describe("identity schema — price tier deletion guard (IT: Price Tier Deletion Guard)", () => {
  let testDb: TestDb;

  beforeEach(async () => {
    testDb = await createTestDb();
    // Catalog schema first (drizzle/0000 ships price_tier, the FK target of
    // users.price_tier_id); drizzle/0001 ships the users DDL on top, in the
    // same order a fresh database applies them.
    await migrate(testDb.db, { migrationsFolder: DRIZZLE_DIR });
  });

  afterEach(async () => {
    await closeTestDb(testDb);
  });

  // IT: Price Tier Deletion Guard — deleting an in-use tier must fail at the
  // database (design.md threat matrix: "Tier deleted while resellers assigned
  // | ON DELETE RESTRICT on users.price_tier_id — database, not app code"),
  // and the tier row must survive the rejected DELETE.
  it("rejects deleting a price tier with assigned resellers, tier remains", async () => {
    const tierId = "aaaaaaaa-1111-4111-8111-111111111111";
    await insertPriceTier(testDb, tierId, "TIER_IN_USE");
    await insertUser(
      testDb,
      "bbbbbbbb-2222-4222-8222-222222222222",
      "guarded@example.com",
      "RESELLER",
      tierId,
    );

    // The constraint NAME is the stable contract: PGlite's dialect reports
    // RESTRICT violations as "violates RESTRICT setting of foreign key
    // constraint \"users_price_tier_id_price_tier_id_fk\"" (SQLSTATE 23001),
    // while real Postgres says "violates foreign key constraint
    // \"users_price_tier_id_price_tier_id_fk\"" (SQLSTATE 23503). Matching the
    // name keeps the assertion true on both.
    await expect(
      testDb.db.execute(sql`DELETE FROM price_tier WHERE id = ${tierId}`),
    ).rejects.toMatchObject({
      cause: expect.objectContaining({
        message: expect.stringMatching(
          /foreign key constraint "users_price_tier_id_price_tier_id_fk"/,
        ),
      }),
    });

    // The tier must still be there — the guard blocks deletion, it does not
    // detach or null out the resellers' reference.
    const result = await testDb.db.execute<{ count: string }>(
      sql`SELECT count(*)::text AS count FROM price_tier WHERE id = ${tierId}`,
    );
    expect(result.rows).toEqual([{ count: "1" }]);
  });

  // Triangulation: the guard is NOT a blanket ban — an unused tier deletes
  // normally. Without this case a hardcoded "always fail" constraint would
  // satisfy the spec scenario; with it, the behavior is proven selective.
  it("allows deleting a price tier with no assigned resellers", async () => {
    const tierId = "cccccccc-3333-4333-8333-333333333333";
    await insertPriceTier(testDb, tierId, "TIER_UNUSED");

    await testDb.db.execute(sql`DELETE FROM price_tier WHERE id = ${tierId}`);

    const result = await testDb.db.execute<{ count: string }>(
      sql`SELECT count(*)::text AS count FROM price_tier WHERE id = ${tierId}`,
    );
    expect(result.rows).toEqual([{ count: "0" }]);
  });

  // 4.13 verification: the generated DDL itself must carry ON DELETE RESTRICT
  // on users.price_tier_id — this is the mechanism the two behavior tests
  // above observe (asserted against the drizzle-kit diff output, the exact
  // code path the future 0001 migration will run).
  it("declares the ON DELETE RESTRICT foreign key on users.price_tier_id in the generated DDL", async () => {
    const result = await testDb.db.execute<{ conname: string; consrc: string }>(
      sql`SELECT conname, pg_get_constraintdef(oid) AS consrc FROM pg_constraint WHERE contype = 'f' AND conrelid = 'users'::regclass`,
    );

    const tierFk = result.rows.filter((row) => row.consrc.includes("price_tier"));
    expect(tierFk).toHaveLength(1);
    expect(tierFk[0].consrc).toContain("ON DELETE RESTRICT");
  });
});

describe("identity schema — reseller deactivation preserves data (IT: Reseller Deactivation Preserves Data)", () => {
  let testDb: TestDb;

  beforeEach(async () => {
    testDb = await createTestDb();
    // Catalog schema first (drizzle/0000 ships price_tier, the FK target of
    // users.price_tier_id); drizzle/0001 ships the users DDL on top, in the
    // same order a fresh database applies them.
    await migrate(testDb.db, { migrationsFolder: DRIZZLE_DIR });
  });

  afterEach(async () => {
    await closeTestDb(testDb);
  });

  // Task 4.15: `deactivated_at` is the ENTIRE deactivation mechanism
  // (design.md: "Reseller deactivated | deactivated_at only — no redundant
  // is_active boolean that could disagree with it"). Asserted against the
  // real 0001 migration applied in beforeEach, so the checked-in DDL cannot
  // drift: the column must exist, be nullable (an active user has NULL;
  // deactivation stamps a timestamp), and there must be no competing
  // boolean flag.
  it("declares a nullable deactivated_at column and no is_active boolean in the generated DDL", async () => {
    const result = await testDb.db.execute<{ column_name: string; is_nullable: string; data_type: string }>(
      sql`SELECT column_name, is_nullable, data_type FROM information_schema.columns WHERE table_name = 'users'`,
    );

    const deactivatedAt = result.rows.find((row) => row.column_name === "deactivated_at");
    expect(deactivatedAt).toBeDefined();
    expect(deactivatedAt!.is_nullable).toBe("YES");
    expect(deactivatedAt!.data_type).toBe("timestamp with time zone");
    expect(result.rows.map((row) => row.column_name)).not.toContain("is_active");
  });
});
