import path from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { sql } from "drizzle-orm";
import { migrate } from "drizzle-orm/pglite/migrator";

import { createTestDb, closeTestDb, type TestDb } from "../../../../tests/support/pglite-db";
import { mintAdminScope, mintResellerScope, type AccessScope } from "../domain/access-scope";
import type { ScopedUserRow, ScopedUsersRepository } from "../domain/scoped-users-repository";
import { DrizzleScopedUsersRepository } from "./drizzle-users-repository";
import { InMemoryScopedUsersRepository } from "./in-memory-users-repository";

/**
 * IT: Reseller Row Isolation — one shared contract suite run twice
 * (design.md "Testing Strategy"): the in-memory fake proves the USE CASE
 * is scoped, PGlite proves the SQL is. Same assertions, both backends.
 *
 * The reseller-owned table is `users` (the ONLY table carrying
 * `reseller_id` — catalog tables are tier-scoped, not reseller-scoped;
 * design.md "Schema" + shared/db/tenant.ts). A row is owned by reseller X
 * when its `reseller_id` is X.
 *
 * Task 4.8 RED: the scoped adapters do not exist yet, so this suite is
 * expected to fail at import resolution. The PGlite leg applies the real
 * migrations (drizzle/0000 + drizzle/0001, generated by M9) rather than
 * deriving the DDL, so the SQL leg exercises the exact schema that ships.
 */
const DRIZZLE_DIR = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "..",
  "..",
  "drizzle",
);

// ── Seed data: two resellers owning two rows each, plus one platform row ──
const TIER_ID = "99999999-9999-4999-8999-999999999999";
const RESELLER_A = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa";
const RESELLER_B = "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb";
const RESELLER_C = "cccccccc-cccc-4ccc-8ccc-cccccccccccc";

const ROWS_A: readonly ScopedUserRow[] = [
  { id: "11111111-1111-4111-8111-111111111111", email: "a-account-1@example.com", role: "RESELLER", resellerId: RESELLER_A, priceTierId: TIER_ID, deactivatedAt: null },
  { id: "22222222-2222-4222-8222-222222222222", email: "a-account-2@example.com", role: "RESELLER", resellerId: RESELLER_A, priceTierId: TIER_ID, deactivatedAt: null },
];

const ROWS_B: readonly ScopedUserRow[] = [
  { id: "33333333-3333-4333-8333-333333333333", email: "b-account-1@example.com", role: "RESELLER", resellerId: RESELLER_B, priceTierId: TIER_ID, deactivatedAt: null },
  { id: "44444444-4444-4444-8444-444444444444", email: "b-account-2@example.com", role: "RESELLER", resellerId: RESELLER_B, priceTierId: TIER_ID, deactivatedAt: null },
];

const ROW_PLATFORM: ScopedUserRow = {
  id: "55555555-5555-4555-8555-555555555555",
  email: "platform@example.com",
  role: "ADMIN",
  resellerId: null,
  priceTierId: null,
  deactivatedAt: null,
};

interface Adapter {
  name: string;
  /** Seeds the same four reseller-owned rows + one platform row. */
  seed(): Promise<void>;
  /** A repository bound to `scope` over the seeded store. */
  repoFor(scope: AccessScope): Promise<ScopedUsersRepository>;
  teardown(): Promise<void>;
}

function inMemoryAdapter(): Adapter {
  let rows: readonly ScopedUserRow[] = [];
  return {
    name: "in-memory fake",
    async seed() {
      rows = [...ROWS_A, ...ROWS_B, ROW_PLATFORM];
    },
    async repoFor(scope) {
      return new InMemoryScopedUsersRepository(rows, scope);
    },
    async teardown() {
      // nothing to dispose
    },
  };
}

function pgliteAdapter(): Adapter {
  let testDb: TestDb | null = null;
  return {
    name: "PGlite (real Postgres)",
    async seed() {
      testDb = await createTestDb();
      // Real migrations, real order: drizzle/0000 (catalog: price_tier is
      // the FK target) then drizzle/0001 (identity: users).
      await migrate(testDb.db, { migrationsFolder: DRIZZLE_DIR });
      // IT: One Price Tier Per Reseller — the users_reseller_requires_tier
      // CHECK accepts a RESELLER row only with an assigned tier; the ADMIN
      // platform row must carry none. The fake leg above models the use case
      // only, so only this SQL leg needs the real invariant.
      await testDb.db.execute(
        sql`INSERT INTO price_tier (id, code, name, created_at) VALUES (${TIER_ID}, 'SEED', 'Seed tier', now())`,
      );
      for (const row of [...ROWS_A, ...ROWS_B, ROW_PLATFORM]) {
        // `password_hash` is NOT NULL (drizzle/0002); a stand-in PHC string
        // keeps this suite about isolation, which is what it proves.
        await testDb.db.execute(
          sql`INSERT INTO users (id, email, password_hash, role, reseller_id, price_tier_id, created_at) VALUES (${row.id}, ${row.email}, '$argon2id$stand-in', ${row.role}, ${row.resellerId}, ${row.role === "RESELLER" ? TIER_ID : null}, now())`,
        );
      }
    },
    async repoFor(scope) {
      return new DrizzleScopedUsersRepository(testDb!.db, scope);
    },
    async teardown() {
      if (testDb) {
        await closeTestDb(testDb);
        testDb = null;
      }
    },
  };
}

describe.each([inMemoryAdapter(), pgliteAdapter()])("ScopedUsersRepository row isolation (IT: Reseller Row Isolation): $name", (adapter) => {
  beforeEach(async () => {
    await adapter.seed();
  });

  afterEach(async () => {
    await adapter.teardown();
  });

  it("returns exactly the rows owned by the reseller for a RESELLER scope (reseller A)", async () => {
    const repo = await adapter.repoFor(mintResellerScope(RESELLER_A, RESELLER_A, "tier-a"));

    const rows = await repo.listUsers();

    expect(rows.map((row) => row.email).sort()).toEqual([
      "a-account-1@example.com",
      "a-account-2@example.com",
    ]);
    expect(rows.every((row) => row.resellerId === RESELLER_A)).toBe(true);
  });

  it("returns NONE of reseller A's rows for reseller B's scope", async () => {
    const repo = await adapter.repoFor(mintResellerScope(RESELLER_B, RESELLER_B, "tier-b"));

    const rows = await repo.listUsers();

    // B owns exactly two rows — the filter ran and excluded A's two rows
    // and the platform row; this is not an accidentally-empty result.
    expect(rows).toHaveLength(2);
    expect(rows.every((row) => row.resellerId === RESELLER_B)).toBe(true);
    expect(rows.map((row) => row.email).sort()).toEqual([
      "b-account-1@example.com",
      "b-account-2@example.com",
    ]);
  });

  it("returns rows from EVERY reseller for an ADMIN scope", async () => {
    const repo = await adapter.repoFor(mintAdminScope("00000000-0000-4000-8000-000000000000"));

    const rows = await repo.listUsers();

    expect(rows).toHaveLength(5);
    expect(new Set(rows.map((row) => row.resellerId))).toEqual(
      new Set([RESELLER_A, RESELLER_B, null]),
    );
  });

  it("returns an empty set for a reseller that owns no rows (isolation is real filtering, not coincidence)", async () => {
    // RESELLER_C owns zero rows while A and B own two each — the emptiness
    // below can only come from the tenant predicate, not from an empty seed.
    const repo = await adapter.repoFor(mintResellerScope(RESELLER_C, RESELLER_C, "tier-c"));

    const rows = await repo.listUsers();

    expect(rows).toEqual([]);
  });
});

// IT: Reseller Deactivation Preserves Data — one shared contract suite run
// twice (fake + PGlite), same as the isolation suite above. Deactivation is
// a soft delete: `deactivated_at` is set, the row is NOT removed, and the
// reseller's owned rows (rows sharing its `reseller_id`) are untouched.
// There is no FK on `users.reseller_id` (design.md DDL lists none — the
// column is the reseller's OWN id for scoping), so nothing cascades from a
// deactivation; the test proves the deactivation path itself only writes
// the target row.
describe.each([inMemoryAdapter(), pgliteAdapter()])(
  "ScopedUsersRepository deactivation (IT: Reseller Deactivation Preserves Data): $name",
  (adapter) => {
    beforeEach(async () => {
      await adapter.seed();
    });

    afterEach(async () => {
      await adapter.teardown();
    });

    it("deactivating a reseller sets deactivated_at and does not remove the row", async () => {
      const repo = await adapter.repoFor(mintAdminScope("00000000-0000-4000-8000-000000000000"));

      const updated = await repo.deactivateUser("11111111-1111-4111-8111-111111111111");

      expect(updated).not.toBeNull();
      expect(updated!.email).toBe("a-account-1@example.com");
      expect(updated!.deactivatedAt).not.toBeNull();

      // Soft delete: the row is still selectable — nothing was removed.
      const rows = await repo.listUsers();
      expect(rows).toHaveLength(5);
      const deactivated = rows.find((row) => row.id === "11111111-1111-4111-8111-111111111111");
      expect(deactivated).toBeDefined();
      expect(deactivated!.deactivatedAt).not.toBeNull();
    });

    it("deactivating a reseller leaves its owned rows present and untouched", async () => {
      const repo = await adapter.repoFor(mintAdminScope("00000000-0000-4000-8000-000000000000"));

      await repo.deactivateUser("11111111-1111-4111-8111-111111111111");

      const rows = await repo.listUsers();
      // The reseller's owned row (same reseller_id) is still there and still
      // active — deactivation must not touch it (accounting data survives).
      const owned = rows.find((row) => row.id === "22222222-2222-4222-8222-222222222222");
      expect(owned).toBeDefined();
      expect(owned!.resellerId).toBe(RESELLER_A);
      expect(owned!.deactivatedAt).toBeNull();
      // Triangulation: another reseller's rows are untouched as well.
      const bRow = rows.find((row) => row.id === "33333333-3333-4333-8333-333333333333");
      expect(bRow!.deactivatedAt).toBeNull();
    });

    it("deactivating an unknown user id is a no-op returning null", async () => {
      const repo = await adapter.repoFor(mintAdminScope("00000000-0000-4000-8000-000000000000"));

      const updated = await repo.deactivateUser("deadbeef-dead-4ead-8ead-deaddeaddead");

      expect(updated).toBeNull();
      const rows = await repo.listUsers();
      expect(rows).toHaveLength(5);
      expect(rows.every((row) => row.deactivatedAt === null)).toBe(true);
    });

    it("a RESELLER scope cannot deactivate a user it does not own (write-path isolation)", async () => {
      // The write path is isolated exactly like the read path: a RESELLER
      // scope's deactivateUser only matches rows it owns, so reseller B
      // cannot deactivate reseller A's account.
      const resellerRepo = await adapter.repoFor(mintResellerScope(RESELLER_B, RESELLER_B, "tier-b"));

      const updated = await resellerRepo.deactivateUser("11111111-1111-4111-8111-111111111111");

      expect(updated).toBeNull();
      // B's scope cannot even READ A's row (read isolation), so the "row
      // untouched" proof goes through an ADMIN scope: A's row must still be
      // active after B's attempted deactivation.
      const adminRepo = await adapter.repoFor(mintAdminScope("00000000-0000-4000-8000-000000000000"));
      const rows = await adminRepo.listUsers();
      const aRow = rows.find((row) => row.id === "11111111-1111-4111-8111-111111111111");
      expect(aRow!.deactivatedAt).toBeNull();
    });
  },
);
