import path from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { migrate } from "drizzle-orm/pglite/migrator";
import { sql } from "drizzle-orm";

import { createTestDb, closeTestDb, type TestDb } from "../support/pglite-db";
import { rollbackLast } from "@/shared/db/migrator";

/**
 * Proves the REAL identity migration (drizzle/0001_*.sql, generated by
 * `npx drizzle-kit generate` from src/shared/db/schema.ts) and its
 * hand-authored down migration (drizzle/down/0001_*.down.sql) apply and
 * roll back cleanly against real Postgres (PGlite), mirroring
 * tests/migrations/catalog-round-trip.test.ts for the catalog schema.
 *
 * Rollback is single-step on purpose: rollbackLast() — the same call the
 * `npm run db:rollback` script makes — must undo ONLY the identity
 * migration (users table + user_role enum), leaving the catalog tables in
 * place.
 */
const DRIZZLE_DIR = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "drizzle",
);

async function publicTableNames(testDb: TestDb): Promise<string[]> {
  const result = await testDb.db.execute<{ table_name: string }>(
    sql`SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' ORDER BY table_name`,
  );
  return result.rows.map((row) => row.table_name);
}

async function userRoleTypeExists(testDb: TestDb): Promise<boolean> {
  const result = await testDb.db.execute<{ exists: boolean }>(
    sql`SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') AS exists`,
  );
  return Boolean(result.rows[0]?.exists);
}

async function roleColumnUsesEnum(testDb: TestDb): Promise<boolean> {
  const result = await testDb.db.execute<{ exists: boolean }>(
    sql`SELECT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = 'users'
        AND column_name = 'role'
        AND udt_name = 'user_role'
    ) AS exists`,
  );
  return Boolean(result.rows[0]?.exists);
}

describe("identity migration round trip (apply both, rollback one)", () => {
  let testDb: TestDb;

  beforeEach(async () => {
    testDb = await createTestDb();
  });

  afterEach(async () => {
    await closeTestDb(testDb);
  });

  it("applies catalog + identity migrations, then rolls back only the identity migration", async () => {
    expect(await publicTableNames(testDb)).toEqual([]);
    expect(await userRoleTypeExists(testDb)).toBe(false);

    await migrate(testDb.db, { migrationsFolder: DRIZZLE_DIR });

    // Both migrations applied: catalog tables still present, users added
    // with its role column wired to the user_role enum.
    expect(await publicTableNames(testDb)).toEqual([
      "plan",
      "plan_price",
      "price_tier",
      "service",
      "users",
    ]);
    expect(await userRoleTypeExists(testDb)).toBe(true);
    expect(await roleColumnUsesEnum(testDb)).toBe(true);

    // Single-step rollback — the exact path `npm run db:rollback` uses.
    const rolledBack = await rollbackLast(testDb.db, DRIZZLE_DIR);

    expect(rolledBack).toEqual("0001_groovy_smiling_tiger");

    // Only the identity layer is gone; the catalog tables survive.
    // The user_role enum REMAINS — documented limitation of the
    // single-statement down-file constraint (see the down file header):
    // DROP TYPE CASCADE leaves a shell table, two statements are rejected
    // by the prepared-statement harness, so the down file drops only the
    // table. This assertion is the tripwire that fails if a future
    // single-statement form makes the enum droppable again.
    expect(await userRoleTypeExists(testDb)).toBe(true);
    expect(await publicTableNames(testDb)).toEqual([
      "plan",
      "plan_price",
      "price_tier",
      "service",
    ]);
  });
});
